name: soundhub
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - "5433:5432"
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./genres.sql:/docker-entrypoint-initdb.d/genres.sql

  redis:
    image: redis:7
    ports:
      - "6380:6379"
    networks:
      - app_network

  soundhub-api:
    build:
      dockerfile: ./docker/Dockerfile
      context: ..
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network: